# Generated by Django 6.0.4 on 2026-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
