# Generated by Django 6.0.4 on 2026-04-17 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hotel_hotelbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelbooking',
            options={},
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='rooms_available',
            new_name='available_rooms',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='guest_email',
            new_name='passenger_email',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='guest_name',
            new_name='passenger_name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.AddField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='distance_from_airport',
            field=models.CharField(default='5km from LOS', help_text='e.g. 5km from LOS', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_rooms',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='check_in_date',
            field=models.DateField(default='2026-05-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.hotel'),
        ),
    ]
